// Auto-generated by scripts/generate-build-info.sh
// Do not edit manually - regenerated on every build

/** Semantic version from package.json */
export const VERSION = '0.0.0'

/** Unique build identifier (git hash + timestamp) */
export const BUILD_ID = '619118a-20260119-224334'

/** ISO timestamp of when build was created */
export const BUILD_DATE = '2026-01-19T22:43:34Z'

/** Short git commit hash */
export const GIT_HASH = '619118a'

/** Display string for UI: "v0.1.0 (a1b2c3d)" */
export const VERSION_DISPLAY = `v${VERSION} (${GIT_HASH})`
