#!/bin/bash
# Generate build info with version, git commit hash, and timestamp
# This script runs before every build (prebuild step in package.json)

set -e

# Get version from package.json
VERSION=$(node -p "require('./package.json').version")

# Get git commit hash (short form)
GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "local")

# Get current timestamp
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
TIMESTAMP=$(date -u +"%Y%m%d-%H%M%S")

# Check if we're in Vercel environment
if [ -n "$VERCEL_GIT_COMMIT_SHA" ]; then
  GIT_HASH="${VERCEL_GIT_COMMIT_SHA:0:7}"
  echo "📦 Vercel build detected - using commit: $GIT_HASH"
fi

# Generate BUILD_ID (for cache busting)
BUILD_ID="${GIT_HASH}-${TIMESTAMP}"

# Write to buildInfo.ts
cat > src/config/buildInfo.ts <<EOF
// Auto-generated by scripts/generate-build-info.sh
// Do not edit manually - regenerated on every build

/** Semantic version from package.json */
export const VERSION = '${VERSION}';

/** Unique build identifier (git hash + timestamp) */
export const BUILD_ID = '${BUILD_ID}';

/** ISO timestamp of when build was created */
export const BUILD_DATE = '${BUILD_DATE}';

/** Short git commit hash */
export const GIT_HASH = '${GIT_HASH}';

/** Display string for UI: "v0.1.0 (a1b2c3d)" */
export const VERSION_DISPLAY = \`v\${VERSION} (\${GIT_HASH})\`;
EOF

echo "✅ Generated build info:"
echo "   Version: v${VERSION}"
echo "   Git Hash: ${GIT_HASH}"
echo "   Build ID: ${BUILD_ID}"
echo "   Location: src/config/buildInfo.ts"
