#!/bin/bash
# Setup local development environment with Supabase
# This script starts Supabase (if needed) and generates .env.development

set -e

echo "🚀 Setting up local development environment..."

# Check if supabase CLI is available
if ! command -v npx &> /dev/null; then
    echo "❌ npx not found. Please install Node.js first."
    exit 1
fi

# Start Supabase if not running
echo "📦 Checking Supabase status..."
if ! npx supabase status &> /dev/null; then
    echo "🔄 Starting Supabase..."
    npx supabase start
else
    echo "✅ Supabase is already running"
fi

# Get Supabase status output
echo "📋 Getting Supabase credentials..."
STATUS_OUTPUT=$(npx supabase status 2>/dev/null)

# Extract values from status output
# The output uses box-drawing characters (│) as separators
# Use awk to split on │ and get the second field (the value)

# API URL - look for "Project URL" row
API_URL=$(echo "$STATUS_OUTPUT" | grep "Project URL" | awk -F'│' '{print $3}' | tr -d '[:space:]')
if [ -z "$API_URL" ]; then
    API_URL="http://127.0.0.1:54321"
    echo "⚠️  Could not extract API URL, using default: $API_URL"
fi

# Anon Key - look for "Publishable" row
ANON_KEY=$(echo "$STATUS_OUTPUT" | grep "Publishable" | awk -F'│' '{print $3}' | tr -d '[:space:]')
if [ -z "$ANON_KEY" ]; then
    echo "❌ Could not extract anon key from supabase status"
    echo "Status output:"
    echo "$STATUS_OUTPUT"
    exit 1
fi

# Service Role Key (for tests) - look for "Secret" row
SERVICE_KEY=$(echo "$STATUS_OUTPUT" | grep "Secret" | awk -F'│' '{print $3}' | tr -d '[:space:]')

# Get Google Client ID from existing .env.local if available
GOOGLE_CLIENT_ID=""
if [ -f ".env.local" ]; then
    GOOGLE_CLIENT_ID=$(grep "VITE_GOOGLE_CLIENT_ID" .env.local 2>/dev/null | cut -d'=' -f2 || echo "")
fi
if [ -z "$GOOGLE_CLIENT_ID" ]; then
    # Use a placeholder - Google OAuth won't work locally anyway without proper setup
    GOOGLE_CLIENT_ID="local-dev-placeholder"
fi

# Generate .env.development
echo "📝 Generating .env.development..."
cat > .env.development << EOF
# Rock On - Development Environment (Local Supabase)
# Generated by scripts/setup-local-env.sh on $(date)
# DO NOT COMMIT - regenerate with: npm run setup:local

# Disable mock auth - use real Supabase auth
VITE_MOCK_AUTH=false
VITE_ENABLE_AUTH=true

# Local Supabase settings (from supabase status)
VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_ANON_KEY=$ANON_KEY

# Google OAuth - use production ID or mock for local
VITE_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
EOF

# Also create .env.test with the service key for E2E tests
echo "📝 Generating .env.test..."
cat > .env.test << EOF
# Rock On - Test Environment (Local Supabase)
# Generated by scripts/setup-local-env.sh on $(date)
# DO NOT COMMIT - regenerate with: npm run setup:local

# Disable mock auth for E2E tests
VITE_MOCK_AUTH=false
VITE_ENABLE_AUTH=true

# Local Supabase settings (from supabase status)
VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_ANON_KEY=$ANON_KEY

# Service role key for admin operations in tests
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY
EOF

echo ""
echo "✅ Environment files generated!"
echo ""
echo "📋 Configuration:"
echo "   VITE_SUPABASE_URL=$API_URL"
echo "   VITE_SUPABASE_ANON_KEY=${ANON_KEY:0:20}..."
if [ -n "$SERVICE_KEY" ]; then
    echo "   SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY:0:20}..."
fi
echo ""
echo "🎯 Next steps:"
echo "   1. Run: npm run env:dev    (switch to development environment)"
echo "   2. Run: npm run dev        (start the dev server)"
echo ""
echo "   Or simply: npm run start:dev"
