/**
 * Show Model
 *
 * Represents gigs, concerts, and live performances.
 * Separated from PracticeSession for clean domain separation.
 *
 * Based on: .claude/specifications/proposed-unified-schema-v2.md (lines 88-200)
 */

export interface Show {
  id: string
  bandId: string
  setlistId?: string
  name: string
  scheduledDate: Date
  duration: number  // Duration in minutes
  venue?: string
  location?: string  // Full address
  loadInTime?: string  // Time string (e.g., "6:00 PM")
  soundcheckTime?: string  // Time string (e.g., "7:00 PM")
  payment?: number  // Payment in cents
  contacts?: ShowContact[]
  status: ShowStatus
  notes?: string
  createdDate: Date
  updatedDate: Date

  // Version tracking for conflict resolution (Phase 3)
  version?: number // Auto-incremented on each update for conflict detection (generated by DB)
  lastModifiedBy?: string // UUID of user who last modified this show
}

export interface ShowContact {
  id: string
  name: string
  role: string  // e.g., "Venue Manager", "Sound Engineer"
  phone?: string
  email?: string
  notes?: string
}

export type ShowStatus = 'scheduled' | 'confirmed' | 'completed' | 'cancelled'

/**
 * Default values for new shows
 */
export const DEFAULT_SHOW_DURATION = 120  // 2 hours in minutes
export const DEFAULT_SHOW_STATUS: ShowStatus = 'scheduled'

/**
 * Helper to create a new show with defaults
 */
export function createNewShow(data: Partial<Show> & Pick<Show, 'bandId' | 'name' | 'scheduledDate'>): Show {
  const now = new Date()

  return {
    id: crypto.randomUUID(),
    duration: DEFAULT_SHOW_DURATION,
    status: DEFAULT_SHOW_STATUS,
    createdDate: now,
    updatedDate: now,
    contacts: [],
    ...data
  }
}

/**
 * Helper to create a new contact with defaults
 */
export function createNewContact(data: Partial<ShowContact> & Pick<ShowContact, 'name' | 'role'>): ShowContact {
  return {
    id: crypto.randomUUID(),
    ...data
  }
}
